# Generated by Django 5.0.3 on 2024-03-30 17:14

import employeeAPI.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeAPI', '0002_alter_addressdetails_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='regid',
            field=employeeAPI.models.CustomAutoField( max_length=6, prefix='EMP'),
            preserve_default=False,
        ),
    ]
