# Generated by Django 5.0.3 on 2024-03-31 07:06

import employeeAPI.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeAPI', '0003_employee_regid'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='regid',
            field=employeeAPI.models.CustomAutoField(editable=False, max_length=6, prefix='EMP'),
        ),
    ]
